services:
  app:
    image: ernesto05itsjr/crud_estudiantes:latest
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin1234@db_stack_e/cetech
    networks:
      - red_swarm_e

networks:
  red_swarm_e:
    external: true
